### PR TITLE
Type class templating system with derive 'a la carte' capabilities

### PR DESCRIPTION
**Pull request by jbgi**
Mostly a workaround for a scalac bug but also force
to be explicit about what is derived from where (see `IOInstances`).

### CODE REVIEW

**Comment by jbgi** [comment]
The bug that is workaound by this patch is one of https://issues.scala-lang.org/browse/SI-8663?jql=resolution%20%3D%20Unresolved%20AND%20text%20~%20%22ClassFormatError%3A%20method%20name%26signature%22
(or a new similar one...)

**Comment by jbgi** [comment]
With this last commit, here are the various way of implementing the Identity Monad:

``` scala
  implicit val identityTheHardWay: Monad[Identity] = new Monad[Identity] {
    override def applicative: Applicative[Identity] = new Applicative[Identity] {
      override def apply: Apply[Identity] = new Apply[Identity] {
        override def functor: Functor[Identity] = new Functor[Identity] {
          override def map[A, B](ma: Identity[A])(f: (A) => B): Identity[B] = Identity(f(ma.run))
        }
        override def ap[A, B](fa: Identity[A])(f: Identity[(A) => B]): Identity[B] = Identity(f.run.apply(fa.run))
      }
      override def pure[A](a: A): Identity[A] = Identity(a)
    }
    override def bind: Bind[Identity] = new Bind[Identity] {
      override def flatMap[A, B](ma: Identity[A])(f: (A) => Identity[B]): Identity[B] = f(ma.run)
      override def apply: Apply[Identity] = applicative.apply
    }
  }
```

``` scala
  implicit val identity: Monad[Identity] = new MonadTemplate[Identity] {
    override def map[A, B](fa: Identity[A])(f: A => B): Identity[B] = Identity(f(fa.run))
    override def ap[A, B](fa: Identity[A])(f: Identity[A => B]): Identity[B] = Identity(f.run.apply(fa.run))
    override def pure[A](a: A): Identity[A] = Identity(a)
    override def flatMap[A, B](oa: Identity[A])(f: A => Identity[B]): Identity[B] = f(oa.run)
  }
```

``` scala
  implicit val identityDeriveMap: Monad[Identity] = new MonadTemplate[Identity] with MonadMap[Identity] {
    override def ap[A, B](fa: Identity[A])(f: Identity[A => B]): Identity[B] = Identity(f.run.apply(fa.run))
    override def pure[A](a: A): Identity[A] = Identity(a)
    override def flatMap[A, B](oa: Identity[A])(f: A => Identity[B]): Identity[B] = f(oa.run)
  }
```

``` scala
  implicit val identityDeriveAp: Monad[Identity] = new MonadTemplate[Identity] with BindAp[Identity] {
    override def map[A, B](fa: Identity[A])(f: A => B): Identity[B] = Identity(f(fa.run))
    override def pure[A](a: A): Identity[A] = Identity(a)
    override def flatMap[A, B](oa: Identity[A])(f: A => Identity[B]): Identity[B] = f(oa.run)
  }
```

``` scala
  implicit val identityDeriveApAndMap: Monad[Identity] =
    new MonadTemplate[Identity] with MonadMap[Identity] with BindAp[Identity] {

      override def pure[A](a: A): Identity[A] = Identity(a)
      override def flatMap[A, B](oa: Identity[A])(f: A => Identity[B]): Identity[B] = f(oa.run)
    }
```

``` scala
  implicit val identityDeriveAllPossible: Monad[Identity] = new MonadClass[Identity] {
    override def pure[A](a: A): Identity[A] = Identity(a)
    override def flatMap[A, B](oa: Identity[A])(f: A => Identity[B]): Identity[B] = f(oa.run)
  }
```

**Comment by aloiscochard** [comment]
Looks great, I would like to think about how to organize all those traits in a simple way before merging. 

For now I m thinking as a pattern such as `MonadClass.Template` and `MonadClass.Ap`. 

Purely organizational, otherwise I'm convinced it's the path we should follow.

**Comment by jbgi** [comment]
make sense! Is the last commit in line with what you were thinking about?

**Comment by aloiscochard** [comment]
merged with 0849f4caab8abceb92c24f0e720377d9762a396c thanks a lot!

**Pull request closed without merging**
