### PR TITLE
Feature/applicative template

### PR DESCRIPTION
**Pull request by aloiscochard**
Here is a proposed `Template` approach to solve two problem:
- Avoid nesting of `vals` to define common class (syntactic sugar)
- Give us a way to encode default implementation

This could be used in place of https://github.com/aloiscochard/scato/pull/2

@jbgi how do you feel about it?

Here I think it makes sense to make the field final, if someone want something else, he can work directly with `Applicative`.

We could argue about fusing the template with the class itself, I'm not sure it is a good idea. It seems safer to go that road, we could anyway fuse them later.

### CODE REVIEW

**Comment by aloiscochard** [comment]
Also, I'm open to alternative suffix than `Template` .

**Comment by aloiscochard** [comment]
I feel like `Class` would be a better suffix: `ApplicativeClass`.

**Comment by jbgi** [comment]
Yeah, naming is hard ;)
I feel that subtyping should be fine for the parallel template hierarchy (templates won't appear as implicits). And that will probably be necessary to achieve good performance.

so maybe something like:

``` scala
trait ApplyTemplate[F[_]] extends Apply[F] with Functor[F] {
  override final def functor = this
}
```

``` scala
trait ApplicativeTemplate[F[_]] extends ApplyTemplate[F] with Applicative[F]  {
  override final def apply = this
  override def map[A, B](fa: F[A])(f: A => B): F[B] = ap(fa)(pure(f))
}
```

(this require to change typeclasses from `abstract class` to `trait` though).
?

**Comment by aloiscochard** [comment]
I'm really suspicious about the performance aspect, and not convince about the benefit of abstraction from subtyping here.

What about composing templates without inheriting?

``` scala
trait ApplicativeTemplate[F[_]] extends Applicative[F]  {
  override final def apply = new ApplyTemplate { ... }
  override def map[A, B](fa: F[A])(f: A => B): F[B] = ap(fa)(pure(f))
}
```

(note: we should remove the final modifier to allow better fine grained composition if needed)

**Comment by aloiscochard** [comment]
Seems like using `Apply` is not necessary the best example, as it does not contains any default implementation from what I can see.

**Comment by aloiscochard** [comment]
I think this designed should be abandoned in favor of: https://github.com/aloiscochard/scato/pull/5

**Pull request closed without merging**
